In [ ]:
# program 1: calculate total weekly energy from  a list
daily_kwh = [400, 850, 400, 350, 500, 600]
total_energy = sum(daily_kwh)
print("Total Energy Used:", total_energy, "kwh")

Total Energy Used: 3100 kwh

In [ ]:
# program 2: Store building usage data
building_usage = {
    "CSE" : 400, "Hostel" : 850
}
print("Hostel used:",building_usage["Hostel"],"kwh")

Hostel used: 850 kwh

In [ ]:
# program 3: A function to calculate electricity cost
def calculate_bill(kwh, rate_per_unit):
  return kwh * rate_per_unit
todays_bill = calculate_bill(400,8)
print("Today's estimated bill is Rs.", todays_bill)

Today's estimated bill is Rs. 3200

In [ ]:
# program 4
import pandas as pd

df = pd.read_excel("campus_energy.xlsx")
print(df)

         Date Building  KWH_USE  PEAK_HOUR_USAGE
0  2026-10-05      CSE      400              510
1  2026-10-06   HOSTEL      900              680
2  2026-10-07      CSE      432              700
3  2026-10-08    CIVIL      600              800
4  2026-10-09     MECH      580              290
5  2026-10-10      ECE      400              800
6  2026-10-11      EEE      820              380
7  2026-10-12   HOSTEL      500              400
8  2026-10-13      CSE      650              790
9  2026-10-14     AIML      740              800
10 2026-10-15     AIDS      820              600
11 2026-10-16    CIVIL      500              850
12 2026-10-17     MECH      740              390
13 2026-10-18      CSE      470              680
14 2026-10-19     AIML      950              500
15 2026-10-20     AIDS      680              600
16 2026-10-21      EEE      840              570
17 2026-10-22      ECE      370              670
18 2026-10-23    CIVIL      760              680

In [23]:

import pandas as pd
from IPython.display import display

df = pd.read_excel("campus_energy.xlsx")
print("Here is the raw data:")
display(df.head())
building_total = df.groupby('Building')['KWH_USE'].sum()

print("Total energy used by each building:")
print(building_total)

print("\nStatistical Summary:")
display(df.describe())

Here is the raw data:

        Date Building  KWH_USE  PEAK_HOUR_USAGE
0 2026-10-05      CSE      400              510
1 2026-10-06   HOSTEL      900              680
2 2026-10-07      CSE      432              700
3 2026-10-08    CIVIL      600              800
4 2026-10-09     MECH      580              290

Total energy used by each building:
Building
AIDS      1500
AIML      1690
CIVIL     1860
CSE       1952
ECE        770
EEE       1660
HOSTEL    1400
MECH      1320
Name: KWH_USE, dtype: int64

Statistical Summary:

                      Date     KWH_USE  PEAK_HOUR_USAGE
count                   19   19.000000        19.000000
mean   2026-10-14 00:00:00  639.578947       615.263158
min    2026-10-05 00:00:00  370.000000       290.000000
25%    2026-10-09 12:00:00  485.000000       505.000000
50%    2026-10-14 00:00:00  650.000000       670.000000
75%    2026-10-18 12:00:00  790.000000       745.000000
max    2026-10-23 00:00:00  950.000000       850.000000
std                    NaN  183.977751       165.977523

In [24]:
# Create the README.md file and write a message inside it
with open("README.md","w") as file:
  file.write("# Smart Campus Energy Project\n")
  file.write("This repository contains my Week 1 hands-on Python and pandas assignments.\n")
  file.write("Created by: []")

print("README.md has been successfully created!")

README.md has been successfully created!